export default function CleanUpText (text){
    text =  text.toString().replace(/(\r\n|\n|\r)/gm, "")
    text =  text.toString().replace('Ã³', 'ó')
    text =  text.toString().replace('Ã¶', 'ö')
    text =  text.toString().replace('Ã£', 'ã')
    text =  text.toString().replace('Ãº', 'ú')
    text =  text.toString().replace('\r\n','')
    text =  text.toString().replace('Ã¡','á')
    text =  text.toString().replace('Ã¡','á')
    text =  text.toString().replace('â€™','"')
    text =  text.toString().replace('â€˜','"')
    text =  text.toString().replace('Ã±', 'ñ')
    text =  text.toString().replace('Ãª', 'ê')
    text =  text.toString().replace('Ä™', 'Ù')
    text =  text.toString().replace('Ã¥', 'å')
    text =  text.toString().replace('Ã¢', 'â')
    text =  text.toString().replace('Ã´', 'ô')
    text =  text.toString().replace('Ãœ', 'Ì')
    text =  text.toString().replace('ÃŸ', 'ß')
    text =  text.toString().replace('Â°', 'ð')
    text =  text.toString().replace('Ã§', 'ç')
    text =  text.toString().replace('Ã«', 'ë')
    text =  text.toString().replace('Å³', 'ó')
    return text
}