export const ACTIONS = {

    LOGIN_USER:"LOGIN_USER",

    LOAD_POSTS:"LOAD_POSTS",
    LOAD_POSTS_SUCCESS:"LOAD_POSTS_SUCCESS",
    LOAD_POSTS_FAIL:"LOAD_POSTS_FAIL",

    EDIT_POST:"EDIT_POST",
    EDIT_POST_SUCCESS:'EDIT_POST_SUCCESS',
    EDIT_POST_FAIL:'EDIT_POST_FAIL',

    LOAD_POST_IMAGES:"LOAD_POST_IMAGES",
    LOAD_POST_IMAGES_SUCCESS:"LOAD_POST_IMAGES_SUCCESS",
    LOAD_POST_IMAGES_FAIL:"LOAD_POST_IMAGES_FAIL"

}