export const ACTIONS = {
    
    CREATE_NEW_CD:"CREATE_NEW_CD_POST",
    CREATE_NEW_CD_SUCCESS:"CREATE_NEW_CD_SUCCESS",
    CREATE_NEW_CD_FAIL:"CREATE_NEW_CD_FAIL",
    EDIT_CD:"EDIT_CD",
    EDIT_CD_SUCCESS:'EDIT_CD_SUCCESS',
    EDIT_CD_FAIL:'EDIT_CD_FAIL',
    DELETE_CD:"DELETE_CD",
    DELETE_CD_SUCCESS:'DELETE_CD_SUCCESS',
    DELETE_CD_FAIL:'DELETE_CD_FAIL',
    UPDATE_CD:"UPDATE_CD",
    UPDATE_CD_SUCCESS:"UPDATE_CD_SUCCESS",
    UPDATE_CD_FAIL:"UPDATE_CD_FAIL",
    UPDATE_CD_IMAGE:"UPDATE_CD_IMAGE",
    UPDATE_CD_IMAGE_SUCCESS:"UPDATE_CD_IMAGE_SUCCESS",
    UPDATE_CD_IMAGE_FAIL:"UPDATE_CD_IMAGE_FAIL",
    UPLOAD_CD_IMAGE:"UPLOAD_CD_IMAGE",
    UPLOAD_CD_IMAGE_SUCCESS:"UPLOAD_CD_IMAGE_SUCCESS",
    UPLOAD_CD_IMAGE_FAIL:"UPLOAD_CD_IMAGE_FAIL",



    CREATE_NEW_POST:"CREATE_NEW_POST",
    CREATE_NEW_POST_SUCCESS:"CREATE_NEW_POST_SUCCESS",
    CREATE_NEW_POST_FAIL:"CREATE_NEW_POST_FAIL",

    CREATE_NEW_POST_IMAGE:"CREATE_NEW_POST_IMAGE",
    CREATE_NEW_POST_IMAGE_SUCCESS:"CREATE_NEW_POST_IMAGE_SUCCESS",
    CREATE_NEW_POST_IMAGE_FAIL:"CREATE_NEW_POST_IMAGE_FAIL",

    CREATE_NEW_PUBLICATION:"CREATE_NEW_PUBLICATION",
    CREATE_NEW_PUBLICATION_SUCCESS:"CREATE_NEW_PUBLICATION_SUCCESS",
    CREATE_NEW_PUBLICATION_FAIL:"CREATE_NEW_PUBLICATION_FAIL",

    INSERT_POST_IMAGE:"INSERT_POST_IMAGE",
    INSERT_POST_IMAGE_SUCCESS:"INSERT_POST_IMAGE_SUCCESS",
    INSERT_POST_IMAGE_FAIL:"INSERT_POST_IMAGE_FAIL",

    LOGIN_USER:"LOGIN_USER",

    LOAD_POST:"LOAD_POST",
    LOAD_POST_SUCCESS:"LOAD_POST_SUCCESS",
    LOAD_POST_FAIL:"LOAD_POST_FAIL",

    LOAD_POSTS:"LOAD_POSTS",
    LOAD_POSTS_SUCCESS:"LOAD_POSTS_SUCCESS",
    LOAD_POSTS_FAIL:"LOAD_POSTS_FAIL",

    LOAD_PRESENTATION:"LOAD_PRESENTATION",
    LOAD_PRESENTATION_SUCCESS:"LOAD_PRESENTATION_SUCCESS",
    LOAD_PRESENTATION_FAIL:"LOAD_PRESENTATION_FAIL",

    LOAD_DASHBOARD_POSTS:"LOAD_DASHBOARD_POSTS",
    LOAD_DASHBOARD_POSTS_SUCCESS:"LOAD_DASHBOARD_POSTS_SUCCESS",
    LOAD_DASHBOARD_POSTS_FAIL:"LOAD_DASHBOARD_POSTS_FAIL",
    
    LOAD_ARTICLE:"LOAD_ARTICLE",
    LOAD_ARTICLE_SUCCESS:"LOAD_ARTICLE_SUCCESS",
    LOAD_ARTICLE_FAIL:"LOAD_ARTICLE_FAIL",

    EDIT_POST:"EDIT_POST",
    EDIT_POST_SUCCESS:'EDIT_POST_SUCCESS',
    EDIT_POST_FAIL:'EDIT_POST_FAIL',

    

    DELETE_POST:"DELETE_POST",
    DELETE_POST_SUCCESS:'DELETE_POST_SUCCESS',
    DELETE_POST_FAIL:'DELETE_POST_FAIL',

    DELETE_POST_IMAGE:"DELETE_POST_IMAGE",
    DELETE_POST_IMAGE_SUCCESS:'DELETE_POST_IMAGE_SUCCESS',
    DELETE_POST_IMAGE_FAIL:'DELETE_POST_IMAGE_FAIL',


    LOAD_EVENTS:"LOAD_EVENTS",
    LOAD_EVENTS_SUCCESS:"LOAD_EVENTS_SUCCESS",
    LOAD_EVENTS_FAIL:"LOAD_EVENTS_FAIL",
   
    LOAD_POST_IMAGE:"LOAD_POST_IMAGE",
    LOAD_POST_IMAGE_SUCCESS:'LOAD_POST_IMAGE_SUCCESS',
    LOAD_POST_IMAGES:"LOAD_POST_IMAGES",
    LOAD_POST_IMAGES_SUCCESS:"LOAD_POST_IMAGES_SUCCESS",
    LOAD_POST_IMAGES_FAIL:"LOAD_POST_IMAGES_FAIL",

    LOAD_PRESENTATIONS:"LOAD_PRESENTATIONS",
    LOAD_PRESENTATIONS_SUCCESS:"LOAD_PRESENTATIONS_SUCCESS",
    LOAD_PRESENTATIONS_FAIL:"LOAD_PRESENTATIONS_FAIL",

    LOAD_ALL_PRESENTATIONS:"LOAD_ALL_PRESENTATIONS",
    LOAD_ALL_PRESENTATIONS_SUCCESS:"LOAD_ALL_PRESENTATIONS_SUCCESS",
    LOAD_ALL_PRESENTATIONS_FAIL:"LOAD_ALL_PRESENTATIONS_FAIL",

    LOAD_CDS:"LOAD_CDS",
    LOAD_CDS_SUCCESS:"LOAD_CDS_SUCCESS",
    LOAD_CDS_FAIL:"LOAD_CDS_FAIL",

    LOAD_CD_INFO:"LOAD_CD_INFO",
    LOAD_CD_INFO_SUCCESS:"LOAD_CD_INFO_SUCCESS",
    LOAD_CD_INFO_FAIL:"LOAD_CD_INFO_FAIL",

    LOAD_CD_AGENDA:"LOAD_CD_AGENDA",
    LOAD_CD_AGENDA_SUCCESS:"LOAD_CD_AGENDA_SUCCESS",
    LOAD_CD_AGENDA_FAIL:"LOAD_CD_AGENDA_FAIL",

    LOAD_AGENDAS:"LOAD_AGENDAS",
    LOAD_AGENDAS_SUCCESS:"LOAD_AGENDAS_SUCCESS",
    LOAD_AGENDAS_FAIL:"LOAD_AGENDAS_FAIL",

    LOAD_ALL_AGENDAS:"LOAD_ALL_AGENDAS",
    LOAD_ALL_AGENDAS_SUCCESS:"LOAD_ALL_AGENDAS_SUCCESS",
    LOAD_ALL_AGENDAS_FAIL:"LOAD_ALL_AGENDAS_FAIL",

    LOAD_MUSIC_CATALOGUE:"LOAD_MUSIC_CATALOGUE",
    LOAD_MUSIC_CATALOGUE_SUCCESS:"LOAD_MUSIC_CATALOGUE_SUCCESS",
    LOAD_MUSIC_CATALOGUE_FAIL:"LOAD_MUSIC_CATALOGUE_FAIL",

    LOAD_MUSIC:"LOAD_MUSIC",
    LOAD_MUSIC_SUCCESS:"LOAD_MUSIC_SUCCESS",
    LOAD_MUSIC_FAIL:"LOAD_MUSIC_FAIL",

    LOAD_MUSIC_PROFILE:"LOAD_MUSIC_PROFILE",
    LOAD_MUSIC_PROFILE_SUCCESS:"LOAD_MUSIC_PROFILE_SUCCESS",
    LOAD_MUSIC_PROFILE_FAIL:"LOAD_MUSIC_PROFILE_FAIL",
    LOAD_MUSIC_PROFILE_BY_ID:"LOAD_MUSIC_PROFILE_BY_ID",

    LOAD_MUSIC_BY_CATEGORY:"LOAD_MUSIC_BY_CATEGORY",
    LOAD_MUSIC_BY_CATEGORY_SUCCESS:"LOAD_MUSIC_BY_CATEGORY_SUCCESS",

    LOAD_ORDER_LOCATIONS:"LOAD_ORDER_LOCATIONS",
    LOAD_ORDER_LOCATIONS_SUCCESS:"LOAD_ORDER_LOCATIONS_SUCCESS",
    LOAD_ORDER_LOCATIONS_FAIL:"LOAD_ORDER_LOCATIONS_FAIL",

    LOAD_EVENT:"LOAD_EVENT",
    LOAD_EVENT_SUCCESS:"LOAD_EVENT_SUCCESS",
    LOAD_EVENT_FAIL:"LOAD_EVENT_FAIL",

    LOAD_EVENTS:"LOAD_EVENTS",
    LOAD_EVENTS_SUCCESS:"LOAD_EVENTS_SUCCESS",
    LOAD_EVENTS_FAIL:"LOAD_EVENTS_FAIL",

    RESET_IMAGE:"RESET_IMAGE",

    UPLOAD_IMAGE:"UPLOAD_IMAGE",
    UPLOAD_IMAGE_SUCCESS:"UPLOAD_IMAGE_SUCCESS",
    UPLOAD_IMAGE_FAIL:"UPLOAD_IMAGE_FAIL",

    UPDATE_EVENT:"UPDATE_EVENT",
    UPDATE_EVENT_SUCCESS:'UPDATE_EVENT_SUCCESS',
    UPDATE_EVENT_FAIL:'UPDATE_EVENT_FAIL',

    UPDATE_POST:"UPDATE_POST",
    UPDATE_POST_SUCCESS:"UPDATE_POST_SUCCESS",
    UPDATE_POST_FAIL:"UPDATE_POST_FAIL",

    UPDATE_POST_IMAGE:"UPDATE_POST_IMAGE",
    UPDATE_POST_IMAGE_SUCCESS:"UPDATE_POST_IMAGE_SUCCESS",
    UPDATE_POST_IMAGE_FAIL:"UPDATE_POST_IMAGE_FAIL",

    UPLOAD_POST_IMAGE:"UPLOAD_POST_IMAGE",
    UPLOAD_POST_IMAGE_SUCCESS:"UPLOAD_POST_IMAGE_SUCCESS",
    UPLOAD_POST_IMAGE_FAIL:"UPLOAD_POST_IMAGE_FAIL",

    UPDATE_PRESENTATION_IMAGE:"UPDATE_PRESENTATION_IMAGE",
    UPLOAD_PRESENTATION_IMAGE:"UPLOAD_PRESENTATION_IMAGE",
    UPLOAD_PRESENTATION_IMAGE_SUCCESS:"UPLOAD_PRESENTATION_IMAGE_SUCCESS",
    UPLOAD_PRESENTATION_IMAGE_FAIL:"UPLOAD_PRESENTATION_IMAGE_FAIL",
    
    UPDATE_PUBLICATION:"UPDATE_PUBLICATION",
    UPDATE_PUBLICATION_SUCCESS:"UPDATE_PUBLICATION_SUCCESS",
    UPDATE_PUBLICATION_FAIL:"UPDATE_PUBLICATION_FAIL",

}